### ISSUE TITLE
Do not version api keys publicly

### ISSUE THREAD

**Issue by InDieTasten** [JasonTheKitten/mzip#1]
https://github.com/JasonTheKitten/mzip/blob/8b50ecd25874b14c68b4f5796ae00754acbcad36/mzip/main.lua#L46

Public git repositories are being scanned by bots to look for keys like this. If you put one up, it's almost certain, that it will be abused by some scraper in the future. Invalidate your current api key, create a new one, and do not commit the new key into a public git repository.

**Comment by JasonTheKitten** [comment]
This is just the key that comes with computercraft 1.80's pastebin program

It can also be found in this repository: https://raw.githubusercontent.com/dan200/ComputerCraft/master/src/main/resources/assets/computercraft/lua/rom/programs/http/pastebin.lua
